### Obtener todos los estudiantes
GET http://localhost:3000/api/students

### Obtener un estudiante por id
GET http://localhost:3000/api/students/1

### Obtener un usuario que no existe
GET http://localhost:3000/api/users/999

### Crear un usuario con contraseña encriptada
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "secureuser@example.com",
  "password": "securepassword",
  "type": "admin"
}

### Crear un usuario con email duplicado
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "duplicate@example.com",
  "password": "password123",
  "type": "user"
}

### Crear un estudiante
POST http://localhost:3000/api/students
Content-Type: application/json

{
  "dni": "11223355E",
  "name": "Jon",
  "last_name": "Moncayola",
  "date_of_birth": "20-07-2000",
  "teacher_id": 2
}

### Intentar borrar un usuario con un profesor asociado
DELETE http://localhost:3000/api/users/1

### Crear un profesor sin estudiantes
POST http://localhost:3000/api/teachers
Content-Type: application/json

{
  "dni": "12345678A",
  "name": "Luis",
  "last_name": "García",
  "date_of_birth": "10-05-1980",
  "user_id": 3
}

### Crear un profesor sin nombre
POST http://localhost:3000/api/teachers
Content-Type: application/json

{
  "dni": "22334455F",
  "last_name": "Martinez",
  "date_of_birth": "15-03-1975",
  "user_id": 2
}

### Intentar borrar un profesor sin estudiantes asociados
DELETE http://localhost:3000/api/teachers/3

### Crear un usuario sin profesor asociado
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "password1234",
  "type": "user"
}

### Intentar borrar un usuario sin profesor asociado
DELETE http://localhost:3000/api/users/4

### Obtener un usuario con su profesor asociado
GET http://localhost:3000/api/users/2

### Crear un usuario con profesor asociado
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "associateduser@example.com",
  "password": "associatedpassword",
  "type": "user",
  "teacher_id": 1
}

### Objetener todos sus estudiantes ordenados por fecha de nacimiento de un profesor
GET http://localhost:3000/api/teachers/1/students



